apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc
  labels:
    app: nextcloud
    tier: backend
    lab: lab4
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # Для minikube будет использоваться default StorageClass

