apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
    tier: database
    lab: lab4
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: postgres
    tier: database

